### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by vadi2** [plasma-umass/cwhy#2]
Could CMake support be considered, so that you can just plug the tool into a codebase with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) and it'll give you the handy explanations automatically?

**Comment by emeryberger** [comment]
I hadn't seen that but you could do this:

```
cmake 2> >(cwhy)
```

The above sends stderr to `cwhy`, which now does nothing if it receives no input.

**Comment by vadi2** [comment]
That worked for the CLI! Any way to do the same in an IDE setup where cmake is invoked for you?

**Comment by emeryberger** [comment]
No doubt it is doable, but I imagine it varies considerably per IDE (and depends on where you want the results to appear). That said, we'd love to see integration into something like Visual Studio.

**Comment by nicovank** [comment]
Closing this as CWhy does not really work at the level where `FetchContent` would be appropriate. Our current CMake support is pretty good IMO.

```bash
% cmake -DCMAKE_CXX_COMPILER=`cwhy --llm=gpt-4 --wrapper --wrapper-compiler=clang++` ...
```
