### ISSUE TITLE
Wrapper mode on Windows

### ISSUE THREAD

**Issue by nicovank** [plasma-umass/cwhy#54]
While trying to integrate CWhy with some GitHub CI, I realize that having a wrapper on Windows is not as straightforward as Linux/MacOS where a `#!` and executable bit are enough.

On Windows, we should probably generate a `.bat` file instead.

**Comment by emeryberger** [comment]
You might want to check out this code from Scalene that may be of assistance: https://github.com/plasma-umass/scalene/blob/ea1bc88f46dae0a6ea87492a7f824b2f722d5818/scalene/redirect_python.py#L24

**Comment by nicovank** [comment]
Fixed in #55 / d61a94854f10922f6c30902a0a2e27d84f3803c4.
