### ISSUE TITLE
Naming test files with the issue may be giving a hint to GPT

### ISSUE THREAD

**Issue by nicovank** [plasma-umass/cwhy#9]
Realized this while showing an example to someone else, the filename was a big hint of what the problem was. The filename is part of the compiler diagnostic so GPT knows, and it could be giving it a hint. In real life of course, the filename will be something unrelated to the problem.

I'll make a small script in the `test` directory to copy the test file to some temporary file and run CWhy on that, this way the filename is some random string and does not give any indication as to what the problem is.

**Comment by emeryberger** [comment]
It would be a good experiment to randomize _all_ the file names in the error message (and even variables and functions) to quantify the impact of names.

**Comment by emeryberger** [comment]
I believe this is all fixed with the anonymizer script so we can close the issue, correct?

**Comment by nicovank** [comment]
Correct. Maybe we can try what you suggested above at some point: randomizing all file names, event standard library ones.

**Comment by emeryberger** [comment]
True, at least as a test.
